name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main
      - 'dependabot/**'

env:
  version: "2.0.2.${{ github.run_number }}${{ github.run_attempt }}"
  build_configuration: "Release"
  build_platform: "x64"

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 10
    outputs:
      version: ${{ steps.set-version.outputs.VERSION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Update Assembly Version
      shell: pwsh
      run: |
        $NewVersion = 'AssemblyVersion("${{ env.version }}")'
        $tmpFile = New-TemporaryFile
        $assemblyInfoPath = "${{ github.workspace }}/PluginMediaMonkey/AssemblyInfo.cs"
        (Get-Content -Path $assemblyInfoPath -Encoding utf8) -replace 'AssemblyVersion\(".*"\)', $NewVersion | Set-Content -Path $tmpFile -Encoding utf8
        Move-Item -Path $tmpFile -Destination $assemblyInfoPath -Force

    - name: Restore Packages
      shell: pwsh
      run: nuget restore MediaMonkey-Rainmeter.sln

    - name: Build x64
      shell: pwsh
      run: |
        msbuild.exe MediaMonkey-Rainmeter.sln /t:Build /nologo /nr:false /p:Version=${{ env.version }} /p:platform="x64" /p:configuration="${{ env.build_configuration }}"
    
    - name: Build x86
      shell: pwsh
      run: |
        msbuild.exe MediaMonkey-Rainmeter.sln /t:Build /nologo /nr:false /p:Version=${{ env.version }} /p:platform="x86" /p:configuration="${{ env.build_configuration }}"

    - name: Move Artifacts
      shell: pwsh
      run: |
        Write-Output "1"
        Get-Childitem "${{ github.workspace }}"
        Write-Output "2"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey"
        Write-Output "3"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey/x64"
        Write-Output "4"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey/x32"
        Write-Output "5"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey/x64/${{ env.build_configuration }}"
        Write-Output "6"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey/x32/${{ env.build_configuration }}"
        Write-Output "7"
        New-Item -Path "${{ github.workspace }}/Deploy/x64" -Type Directory
        Move-Item -Path "${{ github.workspace }}/PluginMediaMonkey/x64/${{ env.build_configuration }}/*" -Destination "${{ github.workspace }}/Deploy/x64" -Force
        
        New-Item -Path "${{ github.workspace }}/Deploy/x32" -Type Directory
        Move-Item -Path "${{ github.workspace }}/PluginMediaMonkey/x32/${{ env.build_configuration }}/*" -Destination "${{ github.workspace }}/Deploy/x86" -Force

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ${{ github.workspace }}/Deploy

  release:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Get plugin - x64
      uses: actions/download-artifact@v3
      with:
        name: build
        path: ${{ github.workspace }}/publish/
        
    - name: Move Artifacts
      shell: pwsh
      run: |
        Move-Item -Path "${{ github.workspace }}/publish/x64/MediaMonkey.dll" -Destination "${{ github.workspace }}/publish/plugin/x64" -Force
        Move-Item -Path "${{ github.workspace }}/publish/x86/MediaMonkey.dll" -Destination "${{ github.workspace }}/publish/plugin/x64" -Force

        
    - name: Zip Files
      run: Compress-Archive -Path "${{ github.workspace }}/publish/plugin/*" -DestinationPath "${{ github.workspace }}/publish/plugin/rainmeter-mediamonkey.v${{ env.version }}.zip"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: releaseartifact
        path: ${{ github.workspace }}/plugin

    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      id: create_release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.run_id }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset 
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}\publish\rainmeter-mediamonkey.v1.2.zip 
        asset_name: AnidbExportParser.zip
        asset_content_type: application/zip
