name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main
      - 'dependabot/**'

env:
  version: "2.0.2.${{ github.run_number }}${{ github.run_attempt }}"
  build_configuration: "Release"
  build_platform: "x64"

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 10
    outputs:
      version: ${{ steps.set-version.outputs.VERSION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Update Assembly Version
      shell: pwsh
      run: |
        $NewVersion = 'AssemblyVersion("${{ env.version }}")'
        $tmpFile = New-TemporaryFile
        $assemblyInfoPath = "${{ github.workspace }}/PluginMediaMonkey/AssemblyInfo.cs"
        (Get-Content -Path $assemblyInfoPath -Encoding utf8) -replace 'AssemblyVersion\(".*"\)', $NewVersion | Set-Content -Path $tmpFile -Encoding utf8
        Move-Item -Path $tmpFile -Destination $assemblyInfoPath -Force

    - name: Restore Packages
      shell: pwsh
      run: nuget restore MediaMonkey-Rainmeter.sln

    - name: Build x64
      shell: pwsh
      run: |
        msbuild.exe MediaMonkey-Rainmeter.sln /t:Build /nologo /nr:false /p:Version=${{ env.version }} /p:platform="x64" /p:configuration="${{ env.build_configuration }}"
    
    - name: Build x86
      shell: pwsh
      run: |
        msbuild.exe MediaMonkey-Rainmeter.sln /t:Build /nologo /nr:false /p:Version=${{ env.version }} /p:platform="x86" /p:configuration="${{ env.build_configuration }}"

    - name: Move Artifacts
      shell: pwsh
      run: |
        Write-Output "1"
        Get-Childitem "${{ github.workspace }}"
        Write-Output "2"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey"
        Write-Output "3"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey/x64"
        Write-Output "3"
        Get-Childitem "${{ github.workspace }}/PluginMediaMonkey/x32"
        Write-Output "4"
        Move-Item -Path "${{ github.workspace }}/PluginMediaMonkey/x64/${{ env.build_configuration }}" -Destination "${{ github.workspace }}/Deploy/x64" -Force
        Move-Item -Path "${{ github.workspace }}/PluginMediaMonkey/x32/${{ env.build_configuration }}" -Destination "${{ github.workspace }}/Deploy/x86" -Force

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ${{ github.workspace }}/Deploy

  release:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Get plugin - x64
      uses: actions/download-artifact@v3
      with:
        name: build
        path: ${{ github.workspace }}/publish/
        
    - name: Move Artifacts
      shell: pwsh
      run: |
        Move-Item -Path "${{ github.workspace }}/publish/x64/MediaMonkey.dll" -Destination "${{ github.workspace }}/publish/plugin/x64" -Force
        Move-Item -Path "${{ github.workspace }}/publish/x86/MediaMonkey.dll" -Destination "${{ github.workspace }}/publish/plugin/x64" -Force

        
    - name: Zip Files
      run: Compress-Archive -Path "${{ github.workspace }}\publish\plugin\*" -DestinationPath "${{ github.workspace }}\publish\plugin\rainmeter-mediamonkey.v${{ env.version }}.zip"
